config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'groups#index', as: :authenticated_root
    end
    unauthenticated do
      root to: 'users#splash', as: :unauthenticated_root
    end
  end

  resources :groups, only: %i[index new create] do
    resources :entities, only: %i[index new create] do
    end
  end
end

app/models/application_record.rb
# top-level documentation comment
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
# top-level documentation comment
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, numericality: { only_integer: true, greater_or_equal_to: 0 }
end

app/models/group.rb
# top-level documentation comment
class Group < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :entities

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/user.rb
# frozen_string_literal: true

# top-level documentation comment
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, length: { maximum: 50 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :entities
end

app/controllers/application_controller.rb
# top-level documentation comment
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/entities_controller.rb
# top-level documentation comment
class EntitiesController < ApplicationController
  before_action :set_user

  def index
    @groups = @user.groups
    @group = @groups.find(params[:group_id])
    @entities = @group.entities
  end

  def new
    @groups = @user.groups
    @group = @groups.find(params[:group_id])
    @entity = Entity.new
  end

  def create
    @group = Group.find(params[:group_id])
    @entity = @user.entities.new(entity_params)

    return unless @entity.save

    redirect_to group_entities_path(@group)
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/groups_controller.rb
# top-level documentation comment
class GroupsController < ApplicationController
  before_action :set_user

  def index
    @groups = @user.groups
  end

  def show
    @group = Group.find(params[:id])
    @entities = []
    @group.entities.order(:id).each do |group_entity|
      @entities << group_entity
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = @user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :image)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/users_controller.rb
# top-level documentation comment
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:splash]
  def splash
    @user = current_user
    redirect_to groups_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
# top-level documentation comment
module ApplicationHelper
end

app/views/entities/_entity_row.html.erb
<div class="flex spc-btwn group-card">
    <div class="flex vert">
        <h4><%= entity.name %></h4>
        <h4 class="text2"><%= entity.created_at.strftime("%d %b %Y") %></h4>
    </div>
    <div>
    <h4 class="text2">$ <%= entity.amount %></h4>
    </div>
</div>

app/views/entities/index.html.erb
<section class="bkg1 full-scrn flex vert cntrd spc-btwn">
  <nav class="navbar">
    <div class="">
      <%= link_to " ⇦ ", authenticated_root_path, :class => 'back-arrow' %>
    </div>

    <div>
      <h3 class="text-white" style="margin-left: 25%">TRANSACTIONS</h3>
    </div>

    <div class="actions">
      <% if user_signed_in? %>
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn3" %>
      <% end %>
    </div>
  </nav>
  
  <div style="height: 100%;">
    <div class="group-card">
      <% if @group.image.attached? %>
        <img src="<%=(url_for(@group.image)) %>", alt="group-image", style="width:60px; height:60px;">
      <% end %>

      <div class="flex vert cntrd">
        <h4><%= @group.name%></h4>
      </div>

      <div>
      </div>
    </div>

    <div class="flex vert cntrd">
      <% @entities.order(created_at: :desc).each do |entity| %>
        <hr>
        <%= render "entity_row", entity: entity %>
      <% end %>
      <hr>
    </div>

    <div class="group-card">
      <h6>Total Amount:</h6>
      <h6> $ <%= @group.entities.sum(:amount) %></h6>
    </div>
  </div>

  <div class="flex vert cntrd green">
    <%= button_to 'ADD NEW TRANSACTION', new_group_entity_path(params[:group_id]), method: :get, class: "text-success btn4" %>
  </div>
</section>

app/views/entities/new.html.erb
<section class="bkg1 full-scrn flex vert cntrd spc-btwn">
    <%= form_with model: @entity, url: group_entities_path(params[:group_id]) do |form| %>
        <nav class="navbar">
            <div class="">
                <%= link_to " ⇦ ", authenticated_root_path, :class => 'back-arrow' %>
            </div>

            <div>
                <h2 class="text-white">ADD NEW TRANSACTION</h2>
            </div>

            <div>
                <%= form.submit "Save", class: "btn btn3" %>
            </div>
        </nav>
    
        <div class="bkg2 flex vert">

        <div>
            <%= form.text_field :name, placeholder:'Name', class:'field1' %>
        </div>
        <hr>
        <div>
            <%= form.number_field :amount, placeholder:'Amount', class:'field1' %>
        </div>
        <hr>
        <div class="field1 flex spc-btwn">
            Select a categorie
            <%= form.select :group_id, options_from_collection_for_select(@groups, :id, :name) %>
        </div>

        </div>
    <% end %>
<section>

app/views/groups/_group_card.html.erb
<li class="flex vert cntrd" style="margin: 5px 0;">
    <div class="group-card">
       <div>
        <% if group.image.attached? %>
            <img src="<%=(url_for(group.image)) %>", alt="group-image", style="width:60px; height:60px;">
        <% end %>
        </div>

        <div class="flex vert cntrd">
          <div><%= link_to group.name, group_entities_path(group), :class => 'text1' %></div>
        </div>
        
        <div class="flex vert cntrd">
            <div>$ <%= group.entities.sum(:amount) %></div>
        </div>
    </div>
</li>

app/views/groups/index.html.erb
<section class="bkg1 full-scrn flex vert">
  <nav class="navbar">
    <div class="flex vert">
      <h6 class="text-white">Signed in</h6>
      <h6 class="text-white">as: <%= @user.name %></h6>
    </div>

    <div>
      <h2 class="text-white" style="margin-left: 15%">CATEGORIES</h2>
    </div>

    <div class="actions">
      <% if user_signed_in? %>
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn3" %>
      <% end %>
    </div>
  </nav>

  <div class="flex vert spc-btwn gap" style="height: 100%;">
    <div class="flex vert" style="width: 100%; flex-wrap: wrap;yy">
      <% @groups.each do |group| %>
        <%= render "group_card", group: group %>
      <% end %>
    </div>

    <div class="flex vert cntrd green">
      <%= button_to 'ADD NEW CATEGORY', new_group_path, method: :get, class: 'btn4'%>
    </div>
  </div>
</section>

app/views/groups/new.html.erb
<section class="bkg1 full-scrn flex vert" style="height: 100%;">
  <%= form_with model: @group, url: groups_path do |form| %>
  
  <nav class="navbar">
    <div class="">
      <%= link_to " ⇦ ", authenticated_root_path, :class => 'back-arrow' %>
    </div>

    <div>
      <h2 class="text-white">ADD NEW CATEGORY</h2>
    </div>

    <div class="">
        <%= form.submit "Save", class: "btn btn3" %>
      </div>
  </nav>

<div class="bkg2 flex vert">


      <div>
        <%= form.text_field :name, placeholder:'Name', :class =>'field1' %>
      </div>
      <div  class="field1">
        <label>Upload Image <%= form.file_field :image, style: 'display:none;' %>
        </label>
      </div>
      
      </div>
  <% end %>
  
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpensesRecordApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-track-turbo": "true", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/splash.html.erb
<section class="flex cntrd spc-btwn vert full-scrn bkg1" style="padding:15% 0 2%">
    <div class="flex cntrd">
       <%= image_tag("app-image.jpg", width: '30%', alt: "Edit Entry") %>
    </div>

    <div>
      <h1 style="font-size: 30px; font-family: 'Fertigo'">My Expenses Record App</h1>
    </div>
    
    <div class="flex vert cntrd spc-arnd gap">
      <%= button_to "SIGN IN", new_user_session_path, method: :get, class: 'btn btn1' %>
      <%= button_to "SIGN UP", new_user_registration_path, method: :get, class: 'btn2' %>
    </div>
</section>